apiVersion: v1
kind: Namespace
metadata:
  name: school

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: school-ingress
  namespace: school
spec:
  ingressClassName: nginx
  rules:
  - host: school.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: school-svc
          servicePort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: school
  namespace: school
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name: school
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: school-svc
  namespace: school
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: school
